name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Store build artifact
      uses: actions/upload-artifact@v2
      with:
        name: static-webserver
        path: /home/runner/work/static-webserver/static-webserver/target/release/static_webserver
    - name: Run tests
      run: cargo test --verbose
